### ISSUE TITLE
Resource leaks in encoder and decoder

### ISSUE THREAD

**Issue by mixalturek** [xiaxiaocao/jvcdiff#7]
There is a resource leak in VcdiffEncoder.encode(File, File, File), FileInputStream for sourceFile is never closed. Others two won't be closed if an exception occurs before entering try-finally section.

VcdiffDecoder.decode(File, File, File) is similar, the streams won't be closed if an exception occurs before entering try-finally section - e.g. if path file doesn't exist.

I will send a pull request with a fix.

**Comment by xiaxiaocao** [comment]
new version 2.0.2
